alias analyse='ipython -i ~/software/RateAnalysis/analyse.py -- $@'
alias DrawCurrents='ipython -i ~/software/RateAnalysis/src/currents.py -- $@'
alias ShowRunplans='python ~/software/RateAnalysis/src/run_selection.py -s'
alias MasterSelection='python ~/software/RateAnalysis/src/run_selection.py -ms'
alias ShowSelection='python ~/software/RateAnalysis/src/DiamondRateScans.py -s -v'
alias ShowSelections='python ~/software/RateAnalysis/src/DiamondRateScans.py -sa -v'
alias RunSelection='ipython -i ~/software/RateAnalysis/src/run_selection.py -- $@'
alias DiaSelection='ipython -i ~/software/RateAnalysis/src/DiamondRateScans.py -- $@'
