[BASIC]
type = pixel
filename = test161000
runpath = /Users/diegoalejandro/Data/psi_2016_10/root/pixel
runinfofile = /Users/diegoalejandro/Data/psi_2016_10/run_log.json
runplaninfofile = Runinfos/run_plans.json
runlog_key_prefix = 
treename = tree
maskfilepath = /Users/diegoalejandro/Data/psi_2016_10/masks
hvdatapath = /Users/diegoalejandro/Data/psi_2016_10/HVClient/
hvconfigfile = /Users/diegoalejandro/Data/psi_2016_10/HV.cfg
createnewrootfiles = True
signalregion_low = 210
signalregion_high = 360
telescopeid = 22

[ROOTFILE_GENERATION]
save_waveforms = 0
pulser_channel = 2
trigger_channel = 1
pulser_drs4_threshold = 80
eudaqfolder = /Users/diegoalejandro/Documents/eudaq/eudaq-drs4
converterFile = 201610/converter_telescope.conf
trackingfolder = /Users/diegoalejandro/Documents/TrackingTelescope/TrackingTelescope
rawfolder = /Users/diegoalejandro/Data/psi_2016_10/raw
rawprefix = run00
converterprefix = test00

